name: Check new version

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 1 * *' # every month first day

jobs:
  check_version:
    uses: mpvkit/BuildShared/.github/workflows/check_version.yml@main
    secrets: inherit
    with:
      repository: 'https://git.savannah.gnu.org/git/readline.git'
      library: 'readline'
